DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (NAME VARCHAR NOT NULL, AGE INTEGER, PRIMARY KEY (NAME));
INSERT INTO "PUBLIC"."PERSON" VALUES ('Peter',  45);
INSERT INTO "PUBLIC"."PERSON" VALUES ('Lois',   41);
INSERT INTO "PUBLIC"."PERSON" VALUES ('Meg',    15);
INSERT INTO "PUBLIC"."PERSON" VALUES ('Chris',  13);
INSERT INTO "PUBLIC"."PERSON" VALUES ('Brian',  6);
INSERT INTO "PUBLIC"."PERSON" VALUES ('Stewie', 0);
