server:
  port: 8080
javax:
  sql:
    DataSource:
      default:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dataSource:
          url: jdbc:h2:mem:app;INIT=RUNSCRIPT FROM 'classpath:META-INF/create.sql'
          user: sa
          password: ""
